### ISSUE TITLE
jobQueue 产生任务的速度慢于处理速度，如何保证能dispatcher?

### ISSUE THREAD

**Issue by aaaasssdd** [LyricTian/queue#2]
func (q *Queue) dispatcher() {
	go func() {
		for job := range q.jobQueue {
			worker := <-q.workerPool
			worker <- job
		}
	}()
}

**Comment by LyricTian** [comment]
`dispatcher`是由工作线程来处理的，任务产生后，就会随机从线程池中随机取出一个工作线程来执行任务。只要服务能够优雅的关闭，在退出之前执行`Terminate`方法，就能保证任务被执行完成。这个线程池的数量一般是根据业务场景来定，我理解的是你想要的答案吗？

**Comment by aaaasssdd** [comment]
多谢
